// The bindings are generated by wayland-scanner's proc macros, which read the
// XML at compile time without telling Cargo about it. Without this, editing only
// the protocol leaves stale generated code behind until something else in this
// crate changes.
fn main() {
    println!("cargo:rerun-if-changed=../../protocols/raven-shell-v1.xml");
}
